<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("STYLE_MODIF", "stores");
$APPLICATION->SetPageProperty("title", "Фирменные магазины и магазины партнеров");
$APPLICATION->SetPageProperty("WIDE_PAGE", "Y");
$APPLICATION->SetPageProperty("description", "Покупайте лакокрасочные материалы от FaMa и BIOFA в наших официальных магазинах и магазинах партнеров.");
$APPLICATION->SetTitle("Фирменные магазины и магазины партнеров");
?><?global $arTheme;?>
<?if($arTheme["STORES_SOURCE"]["VALUE"] != 'IBLOCK'):?>
	<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.store1",
	"main",
	Array(
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "3600000",
		"CACHE_TYPE" => "A",
		"COMPONENT_TEMPLATE" => "main",
		"FILTER_NAME" => "arRegionality",
		"MAP_TYPE" => "0",
		"PHONE" => "Y",
		"SCHEDULE" => "Y",
		"SEF_FOLDER" => "/contacts/stores/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("liststores"=>"","element"=>"#store_id#/",),
		"SET_TITLE" => "Y",
		"TITLE" => ""
	)
);?>
<?else:?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"contacts", 
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "Y",
		"AJAX_OPTION_JUMP" => "Y",
		"AJAX_OPTION_SHADOW" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALSO_ITEMS_COUNT" => "5",
		"ALSO_ITEMS_POSITION" => "bottom",
		"ALT_TITLE_GET" => "NORMAL",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "300000",
		"CACHE_TYPE" => "A",
		"CATEGORY_CODE" => "CATEGORY",
		"CATEGORY_IBLOCK" => array(
			0 => "16",
		),
		"CATEGORY_ITEMS_COUNT" => "5",
		"CATEGORY_THEME_6" => "list",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "contacts",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONVERT_CURRENCY" => "N",
		"COUNT_IN_LINE" => "3",
		"DEFAULT_LIST_TEMPLATE" => "block",
		"DEPTH_LEVEL_BRAND" => "2",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_BLOG_USE" => "N",
		"DETAIL_BRAND_USE" => "Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FB_USE" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "DETAIL_TEXT",
			4 => "DETAIL_PICTURE",
			5 => "ADDRESS",
			6 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "ADDRESS",
			1 => "LINK_REGION",
			2 => "MAP",
			3 => "METRO",
			4 => "SCHEDULE",
			5 => "SITE",
			6 => "PAY_TYPE",
			7 => "PHONE",
			8 => "SITE_STORE",
			9 => "MORE_PHOTOS",
			10 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_USE_COMMENTS" => "Y",
		"DETAIL_VK_USE" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_COMPARE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PANEL" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"ELEMENT_TYPE_VIEW" => "element_4",
		"FILTER_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"FILTER_NAME" => "arRegionLink",
		"FILTER_PROPERTY_CODE" => array(
			0 => "LINK_REGION",
			1 => "MAP",
			2 => "",
		),
		"FORM" => "Y",
		"FORM_BUTTON_TITLE" => "",
		"FORM_ID" => "",
		"FORM_ID_ORDER_SERVISE" => "",
		"GALLERY_PRODUCTS_PROPERTY" => "PHOTOS",
		"GALLERY_TYPE" => "small",
		"GOOGLE_API_KEY" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_CATALOG_ID" => "5",
		"IBLOCK_CATALOG_TYPE" => "-",
		"IBLOCK_ID" => "14",
		"IBLOCK_TYPE" => "aspro_next_content",
		"IMAGE_CATALOG_POSITION" => "left",
		"IMAGE_POSITION" => "left",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LANDING_IBLOCK_ID" => "",
		"LANDING_SECTION_COUNT" => "10",
		"LANDING_TITLE" => "Популярные категории",
		"LINE_ELEMENT_COUNT" => "2",
		"LINE_ELEMENT_COUNT_LIST" => "3",
		"LINKED_ELEMENST_PAGE_COUNT" => "20",
		"LINKED_PRODUCTS_PROPERTY" => "BRAND",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "",
		),
		"LIST_PROPERTY_CATALOG_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "ADDRESS",
			1 => "SITE",
			2 => "",
		),
		"LIST_VIEW" => "slider",
		"MAP_TYPE" => "0",
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "200",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "",
		"PAGER_TITLE" => "Магазины",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PRICE_CODE" => array(
			0 => "",
			1 => "",
		),
		"PRODUCT_PROPERTIES" => "",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SALE_STIKER" => "-",
		"SECTIONS_TYPE_VIEW" => "sections_1",
		"SECTION_ELEMENTS_TYPE_VIEW" => "list_elements_3",
		"SECTION_TYPE_VIEW" => "section_1",
		"SEF_FOLDER" => "/stores/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ARTICLE_SKU" => "N",
		"SHOW_ASK_QUESTION_BLOCK" => "Y",
		"SHOW_CHILD_SECTIONS" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "N",
		"SHOW_DISCOUNT_TIME" => "Y",
		"SHOW_DISCOUNT_TIME_EACH_SKU" => "N",
		"SHOW_FILTER_DATE" => "Y",
		"SHOW_GALLERY" => "Y",
		"SHOW_LINKED_PRODUCTS" => "N",
		"SHOW_MEASURE" => "N",
		"SHOW_MEASURE_WITH_RATIO" => "N",
		"SHOW_NEXT_ELEMENT" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_RATING" => "Y",
		"SHOW_SECTION_DESCRIPTION" => "Y",
		"SHOW_SECTION_NAME" => "N",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SHOW_TABS" => "Y",
		"SHOW_TOP_MAP" => "N",
		"SHOW_UNABLE_SKU_PROPS" => "Y",
		"SORT_BUTTONS" => array(
			0 => "POPULARITY",
			1 => "NAME",
			2 => "PRICE",
		),
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "NAME",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"SORT_PRICES" => "MINIMUM_PRICE",
		"SORT_REGION_PRICE" => "BASE",
		"STIKERS_PROP" => "-",
		"STORES" => array(
			0 => "",
			1 => "",
		),
		"STRICT_SECTION_CHECK" => "N",
		"S_ASK_QUESTION" => "",
		"S_ORDER_SERVISE" => "",
		"TIZERS_IBLOCK_ID" => "",
		"T_ALSO_ITEMS" => "",
		"T_CLIENTS" => "",
		"T_DOCS" => "",
		"T_GALLERY" => "",
		"T_GOODS" => "",
		"T_GOODS_SECTION" => "",
		"T_NEXT_LINK" => "",
		"T_PREV_LINK" => "",
		"T_PROJECTS" => "",
		"T_REVIEWS" => "",
		"T_SERVICES" => "",
		"T_STAFF" => "",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"USE_PERMISSIONS" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"VIEW_TYPE" => "list",
		"CATEGORY_THEME_16" => "list",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_ID#/",
		)
	),
	false
);?>
<?endif;?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>