<?

$APPLICATION->IncludeComponent("bitrix:search.title", 
(isset($arTheme["TYPE_SEARCH"]["VALUE"]) ? $arTheme["TYPE_SEARCH"]["VALUE"] : $arTheme["TYPE_SEARCH"]), 

/*array(
	"NUM_CATEGORIES" => "1",
	"TOP_COUNT" => "10",
	"ORDER" => "date",
	"USE_LANGUAGE_GUESS" => "Y",
	"CHECK_DATES" => "Y",
	"SHOW_OTHERS" => "Y",
	"PAGE" => CNext::GetFrontParametrValue("CATALOG_PAGE_URL"),
	"CATEGORY_OTHERS_TITLE" => "OTHER",
	"CATEGORY_0_TITLE" => "ALL",
	"CATEGORY_0_iblock_aspro_next_catalog" => array(0=>"21",1=>"26",),
	"CATEGORY_0_iblock_aspro_next_content" => array("all"),
	"SHOW_INPUT" => "Y",
	"INPUT_ID" => "title-search-input",
	"CONTAINER_ID" => "title-search",
	"PREVIEW_TRUNCATE_LEN" => "",
	"SHOW_PREVIEW" => "Y",
	"PRICE_CODE" => array("BASE", "OPT"),
	"CONVERT_CURRENCY" => "Y",
	"CURRENCY_ID" => "RUB",
	"PREVIEW_WIDTH" => "25",
	"PREVIEW_HEIGHT" => "25"
	),
*/
	Array(
		"CATEGORY_0" => array(0=>"iblock_aspro_next_catalog",),
		"CATEGORY_0_TITLE" => "",
		"CATEGORY_0_iblock_aspro_next_catalog" => array(0=>"21",1=>"26",),
		"CATEGORY_0_iblock_aspro_next_content" => array(0=>"all",),
		"CATEGORY_1" => array(0=>"iblock_aspro_next_catalog",),
		"CATEGORY_1_TITLE" => "TP",
		"CATEGORY_1_iblock_aspro_next_catalog" => array(0=>"21",),
		"CATEGORY_2" => "",
		"CATEGORY_2_TITLE" => "",
		"CATEGORY_3" => "",
		"CATEGORY_3_TITLE" => "",
		"CATEGORY_4" => "",
		"CATEGORY_4_TITLE" => "",
		"CATEGORY_5" => "",
		"CATEGORY_5_TITLE" => "",
		"CATEGORY_6" => "",
		"CATEGORY_6_TITLE" => "",
		"CATEGORY_7" => "",
		"CATEGORY_7_TITLE" => "",
		"CATEGORY_8" => "",
		"CATEGORY_8_TITLE" => "",
		"CATEGORY_9" => "",
		"CATEGORY_9_TITLE" => "",
		"CATEGORY_OTHERS_TITLE" => "OTHER",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "corp",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONVERT_CURRENCY" => "N",
		"NUM_CATEGORIES" => "1",
		"INPUT_ID" => "title-search-input",
		"CONTAINER_ID" => "title-search",
		"ORDER" => "date",
		"PAGE" => CNext::GetFrontParametrValue("CATALOG_PAGE_URL"),
		"PRICE_CODE" => array(0=>"BASE",),
		"PRICE_VAT_INCLUDE" => "Y",
		"SHOW_ANOUNCE" => "N",
		"SHOW_INPUT" => "Y",
		"SHOW_INPUT_FIXED" => "Y",
		"SHOW_OTHERS" => "N",
		"SHOW_PREVIEW" => "Y",
		"TOP_COUNT" => "4",
		"USE_LANGUAGE_GUESS" => "Y",
		"PREVIEW_WIDTH" => "25",
		"PREVIEW_HEIGHT" => "25"
	),
	false, 
	array("HIDE_ICONS" => "Y")
);

?>