<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Обработка деревянных полов натуральными маслами и восками");
?><br>
 <br>
<div style="height: 90%;">
 <video poster="https://famaprofi.ru/upload/medialibrary/758/0wguvjx86ssevrh8j9pfyyjp1y6uha9s.png" controls=""> <source src="/video/biofa-okraska-parketa.mp4"> </video>
</div>
 <br>
<h5><b><span style="color: #363636; font-size: 15pt;">Обработка деревянных полов натуральными маслами и восками</span></b></h5>
 Для обработки деревянный и паркетных полов внутри помещения, мы рекомендуем натуральные <a href="http://famaprofi.ru/catalog/">масла и воски Biofa</a>.<br>
 <br>
 <span style="color: #383838;"><span style="color: #111111;"><span style="color: #464646;">Масла и воски для напольных покрытий Biofa:<br>
 </span></span></span><span style="color: #383838;"><br>
 </span>
<ul>
	<li>просты в применении</li>
	<li>глубоко проникают в древесину</li>
	<li>создают прочную и износостойкую поверхность</li>
	<li>защищают от влаги, грязи и образований пятен</li>
</ul>
<h6><span style="color: #363636;"><b>Подготовка поверхности к окраске</b></span></h6>
 Перед окраской деревянный пол следует отшлифовать. При обработке неравномерно впитывающих пород древесины, например сосны, рекомендуем перед окраской обработать поверхность <a href="http://famaprofi.ru/catalog/dlya_vnutrennikh_rabot/steny_i_potolki/3754_universalnaya_tverdaya_gruntovka/">Biofa 3754 Универсальная твердая грунтовка</a>. Нанесите грунтовку тонким равномерным слоем при помощи <a href="http://famaprofi.ru/catalog/malyarnyy_instrument/kisti/">кисти</a> или <a href="http://famaprofi.ru/catalog/malyarnyy_instrument/kisti/650001_shchetka_dlya_pola_professionalnaya_s_naturalnym_vorsom_dlya_naneseniya_masla/">щетки для пола</a>, старайтесь вести кисть без отрыва от поверхности по направлению укладки по всей длине помещения, так вы добьетесь наилучшего результата.<br>
 <?$APPLICATION->IncludeComponent(
	"bitrix:catalog.top",
	"products_slider",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_TO_BASKET_ACTION" => "ADD",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPATIBLE_MODE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"OR\",\"True\":\"True\"},\"CHILDREN\":[{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10029\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"3064\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10060\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"5297\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"590\"}}]}",
		"DETAIL_URL" => "",
		"DISPLAY_COMPARE" => "N",
		"ELEMENT_COUNT" => "9",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"ENLARGE_PRODUCT" => "STRICT",
		"FILTER_NAME" => "",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "21",
		"IBLOCK_TYPE" => "aspro_next_catalog",
		"INIT_SLIDER" => "N",
		"LINE_ELEMENT_COUNT" => "3",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"OFFERS_CART_PROPERTIES" => array(),
		"OFFERS_FIELD_CODE" => array("",""),
		"OFFERS_LIMIT" => "5",
		"OFFERS_PROPERTY_CODE" => array("",""),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"PROPERTY_CODE" => array("",""),
		"ROTATE_TIMER" => "30",
		"SALE_STIKER" => "-",
		"SECTION_URL" => "",
		"SEF_MODE" => "N",
		"SHOW_CLOSE_POPUP" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_MEASURE" => "N",
		"SHOW_MEASURE_WITH_RATIO" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PAGINATION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_SLIDER" => "Y",
		"STIKERS_PROP" => "-",
		"TEMPLATE_THEME" => "blue",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"VIEW_MODE" => "SECTION"
	)
);?><br>
<h6><span style="color: #363636;"><b>Окраска деревянного пола цветным маслом</b></span></h6>
 Для придания оттенка поверхности древесины используйте <a href="http://famaprofi.ru/catalog/dlya_vnutrennikh_rabot/mebel_i_stoleshnitsy/8521_04_tsvetnoe_maslo_dlya_interera_med/">цветное масло Biofa color-oil for indoors</a>. Выберите оттенок из представленной палитры или воспользуйтесь услугой подбора цвета. Перед нанесением цветного масла убедитесь, что обрабатываемая поверхность сухая, максимальная допустимая влажность 12%, очищена от грязи, пыли и жира, температура в помещении не должна быть ниже 16 и выше 30 градусов.<br>
 Удалите пыль с поверхности при помощи щетки и пылесоса. Тщательно перемешай продукт. Цветные масла из разных партий следует смешать друг с другом, чтобы не получить разницы в окрашиваемых поверхностях. Всегда делайте пробный выкрас! Производите окрашивание валиком с коротким ворсом или кистью. Наносите масло тонким равномерным слоем, затем удалите или распределите излишки материала по поверхности при помощи белого пада, кисти или валика. <br>
 Обеспечьте хорошую вентиляция воздуха. В процессе сушки не допускайте попадание грязи, влаги и прямых солнечных лучей. Валики кисти и щетки следует промыть <a href="http://famaprofi.ru/catalog/spetsialnye_produkty_biofa/0500_profi_rastvoritel_dlya_udaleniya_smolyanykh_podtekov_i_ochistki_instrumenta_s_dobavlenie_tsitru/">растворителем Biofa 0500</a> и просушить на открытом воздухе, после этого их можно использовать снова. Через 16-20 часов можно наносить следующий слой. Следует убедиться, что масло окончательно высохло. Потрите бумажной салфеткой по окрашенной поверхности и на салфетке не должно остаться следов цветного масла.<br>
 <?$APPLICATION->IncludeComponent(
	"bitrix:catalog.top", 
	"products_slider", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_TO_BASKET_ACTION" => "ADD",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPATIBLE_MODE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"OR\",\"True\":\"True\"},\"CHILDREN\":[{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10084\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"3023\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"3027\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"555\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"566\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"563\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"559\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"545\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10100\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10103\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"5295\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"5296\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10104\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10102\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10101\"}}]}",
		"DETAIL_URL" => "",
		"DISPLAY_COMPARE" => "N",
		"ELEMENT_COUNT" => "17",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"ENLARGE_PRODUCT" => "STRICT",
		"FILTER_NAME" => "",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "21",
		"IBLOCK_TYPE" => "aspro_next_catalog",
		"INIT_SLIDER" => "N",
		"LINE_ELEMENT_COUNT" => "3",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"OFFERS_CART_PROPERTIES" => array(
		),
		"OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_LIMIT" => "5",
		"OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"ROTATE_TIMER" => "30",
		"SALE_STIKER" => "-",
		"SECTION_URL" => "",
		"SEF_MODE" => "N",
		"SHOW_CLOSE_POPUP" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_MEASURE" => "N",
		"SHOW_MEASURE_WITH_RATIO" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PAGINATION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_SLIDER" => "Y",
		"STIKERS_PROP" => "-",
		"TEMPLATE_THEME" => "blue",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"VIEW_MODE" => "SECTION",
		"COMPONENT_TEMPLATE" => "products_slider"
	),
	false
);?><br>
<h6><span style="color: #363636;"><b>Нанесение защитного масла</b></span></h6>
 В зависимости от предполагаемой нагрузки поверхность пола дополнительно следует обработать одним из защитных продуктов Biofa: <a href="http://famaprofi.ru/catalog/dlya_vnutrennikh_rabot/pol_parket_lestnitsy/9062_tverdyy_vosk_maslo_professionalnyy_matovyy/">9062 Твердый воск-масло матовый</a>, <a href="http://famaprofi.ru/catalog/dlya_vnutrennikh_rabot/pol_parket_lestnitsy/9032_tverdyy_vosk_maslo_professionalnyy_shelkovisto_matovyy/">9032 Твердый воск-масло шелковисто-матовый</a>, <a href="http://famaprofi.ru/catalog/dlya_vnutrennikh_rabot/pol_parket_lestnitsy/8624_maslo_dlya_pola_professionalnoe/">8624 масло для пола профессиональное</a>. Чтобы не допустить пожелтения и сохранить оттенок мы рекомендуем добавлять в защитные продукты до 10% цветного масла, использованного ранее. Нанесите масло тонким равномерным слоем велюровым валиком, кистью или щеткой для пола. Предварительно проверьте поверхность на наличие шероховатостей. Если пол недостаточно гладкий, то рекомендуется выполнить промежуточное шлифование при помощи зеленого пада. Обработайте поверхность пола в направлении волокон, тщательно удалите пыль. На следующий день пол можно подвергать легким нагрузкам. Окончательная прочность покрытия достигается через 7-10 дней. В течении этого времени следует защищать поверхность от влаги, грязи и чрезмерных нагрузок. Старайтесь не расстилать ковровые покрытия и не проводить влажную уборку первые 7 дней.<br>
 <?$APPLICATION->IncludeComponent(
	"bitrix:catalog.top",
	"products_slider",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_TO_BASKET_ACTION" => "ADD",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPATIBLE_MODE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"OR\",\"True\":\"True\"},\"CHILDREN\":[{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"551\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"541\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"523\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10097\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10096\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10099\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"5293\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"5294\"}}]}",
		"DETAIL_URL" => "",
		"DISPLAY_COMPARE" => "N",
		"ELEMENT_COUNT" => "9",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"ENLARGE_PRODUCT" => "STRICT",
		"FILTER_NAME" => "",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "21",
		"IBLOCK_TYPE" => "aspro_next_catalog",
		"INIT_SLIDER" => "N",
		"LINE_ELEMENT_COUNT" => "3",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"OFFERS_CART_PROPERTIES" => array(),
		"OFFERS_FIELD_CODE" => array("",""),
		"OFFERS_LIMIT" => "5",
		"OFFERS_PROPERTY_CODE" => array("",""),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"PROPERTY_CODE" => array("",""),
		"ROTATE_TIMER" => "30",
		"SALE_STIKER" => "-",
		"SECTION_URL" => "",
		"SEF_MODE" => "N",
		"SHOW_CLOSE_POPUP" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_MEASURE" => "N",
		"SHOW_MEASURE_WITH_RATIO" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PAGINATION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_SLIDER" => "Y",
		"STIKERS_PROP" => "-",
		"TEMPLATE_THEME" => "blue",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"VIEW_MODE" => "SECTION"
	)
);?><br>
<h6><span style="color: #363636;"><b>Уход и восстановление</b></span></h6>
 Для ухода за окрашенной поверхностью используйте средство <a href="http://famaprofi.ru/catalog/sredstva_po_ukhodu_za_domom/2085_naplana_voskovaya_emulsiya_po_ukhodu_za_polom/">Biofa 2085 naplana</a> 1-2 раза в месяц, для очистки пола применяйте средство <a href="http://famaprofi.ru/catalog/sredstva_po_ukhodu_za_domom/4010_nacasa_universalnoe_chistyashchee_sredstvo/">Biofa 4010 nacasa</a>. Небольшие царапины и повреждения такого покрытия можно просто зашлифовать и вновь обработать маслом без перешлифовки всей поверхности пола.<br>
 <?$APPLICATION->IncludeComponent(
	"bitrix:catalog.top",
	"products_slider",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_TO_BASKET_ACTION" => "ADD",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPATIBLE_MODE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"OR\",\"True\":\"True\"},\"CHILDREN\":[{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10092\"}},{\"CLASS_ID\":\"CondIBXmlID\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10089\"}}]}",
		"DETAIL_URL" => "",
		"DISPLAY_COMPARE" => "N",
		"ELEMENT_COUNT" => "9",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"ENLARGE_PRODUCT" => "STRICT",
		"FILTER_NAME" => "",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "21",
		"IBLOCK_TYPE" => "aspro_next_catalog",
		"INIT_SLIDER" => "N",
		"LINE_ELEMENT_COUNT" => "3",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"OFFERS_CART_PROPERTIES" => array(),
		"OFFERS_FIELD_CODE" => array("",""),
		"OFFERS_LIMIT" => "5",
		"OFFERS_PROPERTY_CODE" => array("",""),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"PROPERTY_CODE" => array("",""),
		"ROTATE_TIMER" => "30",
		"SALE_STIKER" => "-",
		"SECTION_URL" => "",
		"SEF_MODE" => "N",
		"SHOW_CLOSE_POPUP" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_MEASURE" => "N",
		"SHOW_MEASURE_WITH_RATIO" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PAGINATION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_SLIDER" => "Y",
		"STIKERS_PROP" => "-",
		"TEMPLATE_THEME" => "blue",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"VIEW_MODE" => "SECTION"
	)
);?><br>
 <b>Желаем Вам удачной покраски!</b><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>